name: Upload to Archive.org
on: push

jobs:
  job:
    name: Upload
    runs-on: ubuntu-latest
    steps:
     - name: Setup Python
       uses: actions/setup-python@v4
       with:
        python-version: 3.11

     - name: Install dependencies
       run: pip install internetarchive

     - name: Checkout repo
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Create bundle
       run: git bundle create mathvise-${{ github.sha }}.bundle --all

     - name: Upload file to archive.org
       run: |
         ia configure -u ${{ secrets.IA_USER }} -p ${{ secrets.IA_PWD }}
         ia upload mathvise-${{ github.sha }} mathvise-${{ github.sha }}.bundle --metadata="mediatype:software" --metadata="creator:AwesomeKalin" --metadata="title:mathvise-${{ github.sha }}" --metadata="scanner:Mathvise auto-archive" --metadata="collection:open_source_software" --metadata="subject:maths;math;revise;code;node.js;Github" --metadata="originalurl:https://github.com/AwesomeKalin/Mathvise" --retries 20